### ISSUE TITLE
Add RBAC based Feature Flagging

### ISSUE THREAD

**Issue by wilkins88** [wilkins88/ApexLibs#10]
AC:
- Can create a feature flag for Profile, Public Group, Permission Sets or Custom Permissions

**Comment by peternoges** [comment]
@wilkins88 good stuff. Maybe already on your radar, but will feature flags support on/off for role memberships, as well as role subordinate memberships? ie on/off if user has particular userrole.name, or on/off if user’s role exists underneath some role.

**Comment by wilkins88** [comment]
@peternoges It's something I'm tracking in the back of mind, but haven't mapped out yet. Definitely would be a good feature to add. I'll throw something on the backlog!

**Comment by ParzivalWins** [comment]
Where's the roadmap @wilkins88 ?

**Comment by wilkins88** [comment]
@ParzivalWins I don't think I look far enough ahead to have a full roadmap, but I'm maintaining the backlog here: https://github.com/wilkins88/ApexLibs/projects/3
